# Generated by Django 5.1.2 on 2024-12-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileobjapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='filepath',
            field=models.CharField(default='', max_length=100),
        ),
    ]
