# Generated by Django 5.1.2 on 2024-12-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileobjapp', '0003_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='filepath',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
